### ISSUE TITLE
Image is not not being displayed in the website

### ISSUE THREAD

**Issue by rahul-n18** [tattle-made/OGBV#234] opened 2023-03-15 11:41 UTC
**Describe the bug**
The described Image is not displayed in the website

**To Reproduce**
1. Go to 'https://tattle.co.in/products/ogbv'

**Expected behavior**
There is expected to be an Image displayed

**Screenshots**
![Screenshot (9)](https://user-images.githubusercontent.com/64891042/225297929-4e6bec1e-ab82-4ebf-bed2-25114ec9b7e1.png)

**Comment by rahul-n18** [comment] 2023-03-15 11:41
Can I work on this Issue as this is my first work in this Repo

**Comment by Bhargav-Dave** [comment] 2023-03-15 12:56
Hey @rahul-n18! Thanks for flagging the issue and offering help on the same! 

Yes, you can work on the same, the code for that website can actually be found over here: https://github.com/tattle-made/website/blob/master/src/pages/products/ogbv.mdx

The issue it seems is of a broken image link. You can find the image that it references over here: https://github.com/tattle-made/OGBV/blob/main/uli-website/static/Uli_Logo.png

Fork the repo, and create a PR with your changes. Let me know over here if you need some help!

**Comment by rahul-n18** [comment] 2023-03-15 14:51
Sure, and thank you

**Comment by Bhargav-Dave** [comment] 2023-03-16 10:06
Hi @rahul-n18. It would be great if you can create an issue on the website repository and push your code there. Just paste a link to this issue in the description for documentation purposes. Thanks!

**Comment by tarunima** [comment] 2023-03-31 06:12
@rahul-n18 @Bhargav-Dave should we close this issue?

**Comment by Bhargav-Dave** [comment] 2023-03-31 11:26
The issue is fixed here by @rahul-n18: https://github.com/tattle-made/website/pull/107
Closing this

**Closed by Bhargav-Dave** 2023-03-31 11:26 UTC
Labels: bug
