### ISSUE TITLE
[Chrome plugin] Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'slurList')

### ISSUE THREAD

**Issue by duggalsu** [tattle-made/OGBV#152] opened 2022-07-17 18:45 UTC
Error shown in the extensions panel on loading twitter.com

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'slurList')
Context
https://twitter.com/home
Stack Trace
content-script.js:7 (anonymous function)
```

Could not find any resolution on a quick search. Existing issues were related to background worker when using Chrome APIs in a content script.

**Comment by dennyabrain** [comment] 2022-08-26 06:11
closing as i could not reproduce it on this [release](https://github.com/tattle-made/OGBV/releases/tag/v0.1.8). feel free to open if i'm wrong.

**Closed by dennyabrain** 2022-08-26 06:11 UTC
